# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('Country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=30)),
                ('Title', models.CharField(max_length=30)),
                ('Publisher', models.CharField(max_length=30)),
                ('PublishDate', models.DateField()),
                ('Price', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='Books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Book'),
        ),
    ]
